listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.exec_cmd("hyprlock")'
    on-resume = dunstify -u normal "Resume" "Welcome back!"
    #on-resume = hyprctl notify 5 5000 0 "fontsize:20 Welcome back!"
}

listener {
    timeout = 1200
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
