$font = Noto Sans

general {
    hide_cursor = true
    trim_text = true
}

animations {
    enabled = true
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 2, linear
}

background {
    path = $HOME/Documents/wallpapers/change/a_computer_room_with_a_desk_and_a_computer_monitor.jpg
    blur_passes = 1
}

label {
    # text = cmd[update:1000] echo "$(date +'%H:%M')"
    text = <b>$TIME</b>
    color = rgba(255, 255, 255, 1.0)
    font_size = 90
    font_family = $font

    position = 0, 80
    halign = center
    valign = center
}

input-field {
    size =  300, 50
    outline_thickness = 2
    dots_size = 0.15
    dots_spacing = 0.25
    outer_color = rgba(255, 255, 255, 0.5)
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(255, 255, 255, 1.0)
    font_family = $font

    fade_on_empty = false
    rounding = 15

    position = 0, 0
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] echo "$(uptime -p)"
    color = rgba(255, 255, 255, 1.0)
    font_size = 16
    font_family = $font

    position = 0, 10
    halign = center
    valign = bottom
}
