listener {
    timeout = 300
    on-timeout = hyprctl dispatch exec hyprlock
    on-resume = dunstify -u normal "Resume" "Welcome back!"
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
