#!/bin/bash

# Add folders here
vimdir="$HOME/.vim"
aladir="$HOME/.config/alacritty"

# Add symlink paths here
declare -a symlinks=(
"$PWD/bashrc $HOME/.bashrc"
"$PWD/bash_profile $HOME/.bash_profile"
"$PWD/xinitrc $HOME/.xinitrc"
"$PWD/inputrc $HOME/.inputrc"
"$PWD/vimrc $vimdir/vimrc"
"$PWD/tmux.conf $HOME/.tmux.conf"
"$PWD/git-prompt.sh $HOME/.git-prompt.sh"
"$PWD/alacritty.yml $HOME/.config/alacritty/alacritty.yml"
"$PWD/taskrc $HOME/.taskrc"
"$PWD/lynx/lynx.cfg $HOME/.config/lynx/lynx.cfg"
"$PWD/lynx/lynx.lss $HOME/.config/lynx/lynx.lss"
"$PWD/mutt $HOME/.mutt"
)

checkDir() {
  if [[ ! -d "$1" ]]; then
    mkdir -p "$1"
    if [[ $? -eq 0 ]]; then
      printf %s\\n "Creating directory: $1"
    fi
  else
    printf %s\\n "directory: $1 already exists"
  fi
}

checkDir "${vimdir}"
checkDir "${aladir}"

# Create the symlink
for i in "${symlinks[@]}"; do
  ln -sf $i
  if [[ $? -eq 0 ]]; then
    printf %s\\n "Creating symlink: ${i}"
  else
    printf %s\\n "Failed to create symlink: ${i}"
  fi
done
