#!/bin/bash

# Create the sym links to $HOME
ln -s "$HOME/repos/dotfiles/bashrc" "$HOME/.bashrc"
ln -s "$HOME/repos/dotfiles/init.vim" "$HOME/.config/nvim/init.vim"
ln -s "$HOME/repos/dotfiles/xinitrc" "$HOME/.xinitrc"
