#!/bin/sh

case "$1" in
  d)
    shift
    exec lynx "https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$(urlencode "$@")"
    ;;
  g)
    shift
    exec lynx "https://www.google.com/search?q=$(urlencode "$@")"
    ;;
  sh)
    exec lynx "https://www.grymoire.com/Unix/Sh.html"
    ;;
  *)
    echo "Use:
    d for duckduckgo
    g for google
    sh for POSIX shell Guide"
    ;;
esac
