#!/usr/bin/env bash

commands="view pull"
path="${HOME}/programing/python/jackpotAnalyzer"

if test -n "$COMP_LINE"; then
  pre="${COMP_LINE##* }"
  for c in ${commands}; do
    test -z "${pre}" -o "${c}" != "${c#"${pre}"}" && echo "$c"
  done
  exit
fi

case "$@" in
  view)
    cd "${path}" || exit 1
    uv run view.py
    ;;
  pull)
    cd "${path}" || exit 1
    git pull --quiet
    ;;
  *) 
    cd "${path}" || exit 1
    uv run main.py
    [[ -n $(git status --short) ]] || exit 1
    echo "Adding new numbers to git"
    git add data.csv &>/dev/null
    git commit -m "new numbers added" &>/dev/null
    git push &>/dev/null
    ;;
esac
