#!/usr/bin/env bash

commands="go view "

if [[ -n "$COMP_LINE" ]]; then
  pre="${COMP_LINE##* }"
  for c in ${commands}; do
      [[ -z "${pre}" || "${c}" != "${c#"${pre}"}" ]] && echo "$c"
  done
  exit
fi

case "$@" in
    go)
        pushd ~/repos/dotfiles/scripts/ 2>&1 1>/dev/null
        ./jackpot.go
        ;;
    view)
        pushd ~/programing/python/jackpotAnalyzer 2>&1 1>/dev/null
        uv run view.py
        ;;
    *)
        pushd ~/programing/python/jackpotAnalyzer 2>&1 1>/dev/null
        uv run main.py
        ;;
esac

popd 2>&1 1>/dev/null
