#!/bin/sh

test ! -x $(command -v pandoc) && echo "Install Pandoc" && exit 1

exec pandoc -s --from markdown \
  -V 'geometry:margin=1in' \
  -V 'fontsize=10pt' \
  --pdf-engine=pdflatex \
  --template="$HOME/Documents/pandoc-templates/eisvogel.latex" \
  --listings \
  --toc "${1}" -o "${2}"


# Optional
#
#  -V 'mainfont:DejaVuSansMono.ttf' \
