#!/usr/bin/bash

reset=$'[0m'
cyan=$'[34m'
magenta=$'[35m'
yellow=$'[33m'

printf "${cyan}Path!${reset}\n"
printf "${PATH//:/\\n}\n\n"
printf "${yellow}CD Path!${reset}\n"
printf "${CDPATH//:/\\n}\n\n"
printf "${magenta}Go Path!${reset}\n"
printf "${GOPATH//:/\\n}\n\n"
