#!/usr/bin/bash

TITLE="DONE!"
ETITLE="ERROR!"
MESSAGE="All file in the PlexMedia Library are now\nupdated with the right owner and rights!"
ERROR="Something went wrong!\nCheck it out!"

sudo chown -R plex:users /home/plexmedia/
if [ $? -eq 1 ]; then
    notify-send -u critical "${ETITLE}" "${ERROR}"
    exit 1
fi

sudo chmod -R 755 /home/plexmedia
if [ $? -eq 1 ]; then
    notify-send -u critical "${ETITLE}" "${ERROR}"
    exit 1
else
    notify-send -u normal "${TITLE}" "${MESSAGE}"
    exit 0
fi
