#!/bin/sh

qn_file="$HOME/repos/notes/quick_notes.md"

if [[ "$1" == "e" ]]; then
  $EDITOR "${qn_file}"
  exit 0
elif [[ "$1" == "v" ]]; then
  cat "${qn_file}"
  exit 0
elif [[ -z "$1" ]]; then
  echo -e "Usage:
  qn \"<note>\"\tadd a new note
  qn e\t\tEdit note
  qn v\t\tView note files"
  exit 1
fi

echo -e "# $(date '+%Y-%m-%d %H:%M')" >> "${qn_file}"
echo -e "$1\n" >> "${qn_file}"
