#!/bin/sh

qn_file="$HOME/repos/notes/quick_notes.md"
dir="$REPOS/notes"

if [ "$1" = "e" ]; then
  $EDITOR "${qn_file}"
  exit 0
elif [ "$1" = "v" ]; then
  exec cat "${qn_file}"
  exit 0
elif [ -z "$1" ]; then
  echo "Usage:
  qn \"<note>\"\tadd a new note
  qn e\t\tEdit note
  qn v\t\tView note files"
  exit 1
fi

echo "# $(date '+%Y-%m-%d %H:%M')" >> "${qn_file}"
echo "$1\n" >> "${qn_file}"

cd "$dir"

git add -A "$dir"
git commit -m "Updated to quick notes"
git push
