#!/bin/bash
# Depends on the twitch-cli command from https://github.com/twitchdev/twitch-cli

set -e

file="$1"
defultFile="$HOME/streams"

[[ -z $(command -v twitch) ]] && echo "You need to install twitch-cli from https://github.com/twitchdev/twitch-cli" && exit 1
[[ ! -s "$defultFile" ]] && echo "You have to populate your $defultFile with streamer names" && exit 1
[[ -z "$1" ]] && file=$defultFile

declare -a streamerArray

echo "Checking which streamers are live!"
echo "----------------------------------"

while read -r streamer; do
  if [[ $(twitch api get streams -uq user_login="$streamer") =~ (\"type\"\:\"live\") ]]; then
#     echo "$streamer is ${BASH_REMATCH[0]: -5:4}"
    streamerArray+=("$streamer")
  fi
done < "$file"

PS3="Select a streamer to watch: "

select opt in "${streamerArray[@]}" quit; do
  case $opt in
    quit)
      exit 0
      ;;
    *)
      xdg-open "https://twitch.tv/$opt"
      exit 0
      ;;
  esac
done
