#!/bin/sh

# Settings
FILE="test-mic.wav"
REC_TIME=5
SLEEP_TIME=2

# Runtime
echo "Recording for $REC_TIME sec, say somthing!"
arecord -d "$REC_TIME" "$FILE"
echo "Recording STOPED!"
sleep "$SLEEP_TIME"
echo "Playing the recording back to you!"
aplay "$FILE"
echo "all done!"
