#!/bin/sh

tmuxpath=/usr/bin/tmux

if [ ! -x "$tmuxpath" ]; then
  echo "Doesn't look like tmux is installed."
  exit 1
fi

commands="start "

if test -n "$COMP_LINE"; then
  pre="${COMP_LINE##* }"
  for c in ${commands}; do
    test -z "${pre}" -o "${c}" != "${c#${pre}}" && echo "$c"
  done
  exit
fi

case "$@" in
  start)
    exec tmux -L main new -s main -n weechat \ weechat \; new-window -a \; last-window;
    ;;
  *) 
    exec tmux -L main attach
    ;;
esac
