#!/bin/sh

reset='\e[0m'
red='\e[31m'

doGitUpdate() {
  cd "$HOME/${1}" 2>/dev/null || exit 1

  git add -A .
  git commit -m "updated ${1}"
  git push

  cd - || exit 1
}

doGitUpdate ".task"
doGitUpdate ".weechat"
