#!/bin/sh

# This script is used for uncommenting lines in vim combined with the bang (!)
# command. This will remove a hash-tag (#) at the begining of the line.

while IFS= read -r line; do
  echo "${line#* }"
done
