#!/bin/sh

# This script is used for uncommenting lines in vim combined with the bang (!)
# command. This will insert a hash-tag (#) to be used as a comment line.

while IFS= read -r line; do
  echo "${line#* }"
done
