#!/bin/sh

commands="up down status "

if test -n "$COMP_LINE"; then
  pre="${COMP_LINE##* }"
  for c in ${commands}; do
    test -z "${pre}" -o "${c}" != "${c#${pre}}" && echo "$c"
  done
  exit
fi

cmd() {
	mullvad "$1"
	sleep 0.5
	mullvad status
}

case "$@" in
  up)
	cmd "connect"
    ;;
  down)
	cmd "disconnect"
	;;
  status)
	mullvad status
	;;
  *) 
	echo "Usage: vpn [up|down|status]"
esac
