#!/bin/sh
set -e

# Add the following to bashrc to enable completion:
#
#   complete -C zet zet
#
# Note that you will need one such complete line for every multicall
# variation of this script (ex: ln -s zet log; complete -C log log)

test -z "$KN" && echo "KN (knowledge directory) not set." && exit 1
test -z "$GITUSER" && echo "GITUSER not set." && exit 1

EXE=${0##*/}
test -z "$EXE" && echo "Could not determine name of executable." && exit 1

# Add creates a Zettelkasten repo entry with an isosec unique directory
# name within the $KN/$EXE parent directory. Whatever the effective name
# of the executable (multicall, symlink, hardlink, alias, copy) will be
# used for $EXE. Opens editor with $EDITOR or vim.  Git commits using
# the first 50 characters of the first line (ignoring heading hashtags
# if prefixed) and pushes. Designed to be used in situations where
# commiting and pushing to main/master is allowed (which is usually fine
# for knowledge repos).

add() {
  test ! -d "$KN/$EXE" && echo "Directory not found: $KN/$EXE" && exit 1
  dir="$KN/$EXE/$(isosec)"
  mkdir -p "$dir"
  ${EDITOR:-vim} "$dir/README.md"
  cd "$dir"
  test ! -e "$dir/README.md" && rmdir "$dir"
  line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
  test -n "$line"
  echo "Adding: $line"
  git add -A "$dir"
  git commit -m "$line"
  git push
}

query() {
  test -z "$1" && echo "Missing search query." && exit 1
  type urlencode >/dev/null 2>&1
  term="$*"
  it="https://github.com/$GITUSER/$EXE/search?q=$(urlencode $term)"
  ${BROWSER:-echo} "$it"
  echo "[$term]: <$it>"

  # I dont have, use or intent to use rwxrob's wee script
  # So the two below lines are not needed in my use case
  # I should remove them at some point

  # type wee >/dev/null 2>&1 || return 0
  # exec wee "$it"
}

lquery() {
  test -z "$1" && echo "Missing local search query." && exit 1
  term="$*"
  echo "[$term]"
  # Rip grep is required otherwise change rg to grep
  rg -i "$*" $KN/zet/
}

case "$1" in
  add | "") add ;;
  q | query)
    shift
    query "$@"
    ;;
  l | local | lquery)
    shift
    lquery "$@"
    ;;
  *) echo Unsupported. ;;
esac
